version: '3'

services:
  nodejs:
    build:
      context: .              # Use the current directory as the build context
      dockerfile: Dockerfile  # Use the provided Dockerfile
    image: your-nodejs-app  # Replace with your desired image name
    ports:
      - "3000:3000"          # Map port 3000 in the container to the host

  nginx:
    image: nginx:latest
    ports:
      - "80:80"              # Map port 80 in the container to the host
    volumes:
      - ./nginx-config:/etc/nginx/conf.d  # Mount Nginx configuration

